### ISSUE TITLE
"You are an invalid entity and can not travel through the portal"

### ISSUE THREAD

**Issue by Curunir** [Darkhax-Minecraft/Hunting-Dimension#10]
I am getting the above error in chat (numerous times) whenever I try to sneak through the Hunting Dimension portal on my work-in-progress pack. Here are some version details:

Hunting Dimension 1.0.17
Bookshelf 2.5.533
Forge 14.23.2.2624
using Foamfix Anarchy 0.9.2
Minecraft 1.12.2

It's a big pack with 190 mods currently as counted by Forge. I haven't tried Hunting Dimension before, so apologies if I am just using it wrong. The portal can be built and activated fine, using a Tinker's Construct sword to ignite it. I rebuilt and ignited it again with a vanilla Wooden Sword, just to compare, but the result was the same. It won't let me enter. So far only trying in singleplayer, as I am developing and testing my personal pack on 1.12.2. There are no crashes, just an ignited portal that refuses to let the player through.
Tell me if you'd like my modlist or something else that I can provide. Of the mods that mess with the player model, I have Galacticraft in the pack. So far haven't tried removing that, but I guess that'll be my next troubleshooting attempt.

**Comment by Curunir** [comment]
Ok, that was easy. It is indeed resolved by removing Galacticraft. I recall that PlayerAPI was used to work around these things in earlier versions, but apparently it's only available up to 1.12.1 right now:
https://minecraft.curseforge.com/projects/player-api

If you leave this ticket open, I'll update it with my findings once Player API is available. Not sure if reporting the issue to Galacticraft developers makes sense, though.

**Comment by Darkhax** [comment]
You can use the 1.12.1 version of player-api on 1.12.2. Although since this issue gets reported so much I am going to look into changing the requirements on my end to be less strict.

**Comment by Darkhax** [comment]
This issue was resolved in https://github.com/Darkhax-Minecraft/Hunting-Dimension/commit/4c9ae509e1a414ddd0682e1aeee9206c033da075
