### ISSUE TITLE
Suggestion: Config option to spawn with block platform in Hunting Dimension

### ISSUE THREAD

**Issue by Curunir** [Darkhax-Minecraft/Hunting-Dimension#11]
I looked at the config file, and the biome and worldgen options are basically fine. However, there are modpacks - like mine - where the Hunting Dimension will ocasionally just be one huge ocean, or possibly a skyblock/void dimension. To not fall flat in such cases gameplay-wise, I suggest spawning players with a few blocks under their feet at least on first entry. In case a return portal is meant to be present, well, I got none in my "waterworld". So my thinking is, the config file should/could have both an option to create a return portal and a dirt/whatever platform underneath for those edge cases. Disable them by default if you will, but they would be greatly appreciated. Keep in mind that while arrows should be fairly easy to come by, some worldgen may be entirely woodless, so players without spare portal or wood blocks to craft them will be stranded in those.

**Comment by Darkhax** [comment]
Thanks for the suggestion. I am currently not very satisfied with the portal and I plan to rework it in the next update major. I don't know when that will be though.

**Comment by Darkhax** [comment]
After testing the portal out in a void world myself, it seems my portal inherits this property from the vanilla portal. The portal has to spawn a few blocks in the air for it to trigger.

![unknown](https://user-images.githubusercontent.com/2250798/45912693-d8103700-bde2-11e8-9888-7101ae1a90c8.png)
