### ISSUE TITLE
Dim doesn't load

### ISSUE THREAD

**Issue by MavDarkness** [Darkhax-Minecraft/Hunting-Dimension#16]
HuntingDimension-1.12.2-1.0.20
Bookshelf-1.12.2-2.3.539
Forge: 2561
Pack: Sevtech-ages 3.0.6

the pack loads fine and havent had any problems with anything except going into this hunting dim. the dim doesnt seem to load. also while in that picture i did use some commands, /forge tps showed that the world didnt seem to load, had 0 mean tick time. and /home was the only way to get out of that to get back home and continue playing. this is on a server and you are welcome to give it a try yourself. i can tp you to a portal and advance your advancements so that you are able to pass through. just join the server at ghast.hammergaming.com:25566 and type this to get my attention: @MavDarkness#6572
https://prnt.sc/j7mhoc

**Comment by Darkhax** [comment]
This is weird because I have played with SevTech 3.0.6 on a server and have set up a portal to my dimension without any issue. Did you add or remove any mods? The dimension is also staged so you can't just use your friends portal if you don't have the stages yourself.

**Comment by MavDarkness** [comment]
i have the advancements to go in and can go in but the world just doesnt load up. no mods were removed, ftbutils was added along with its dependancy ftblib both at version 5.0.2.10. i am dev for the server, you can join if you want to see for yourself

**Comment by MavDarkness** [comment]
Were you able to reproduce?

**Comment by Darkhax** [comment]
No I still have not managed to reproduce this. It's working fine in my single player world and on the SevTech world still.

**Comment by Darkhax** [comment]
It seems this issue was fixed [here](https://github.com/Darkosto/SevTech-Ages/issues/1984).
> when i made the server i enabled everything through MCMA all the mobs difficulty and whatnot but the only thing that wasnt enabled was the nether/dims
