### ISSUE TITLE
Can't stop rain in Hunting Dimension...

### ISSUE THREAD

**Issue by monodemono** [Darkhax-Minecraft/Hunting-Dimension#17]
Minecraft: 1.12.2
Pack: Sevtech 3.0.7
Mod version: 1.0.24
Multiplayer server
Java: 1.8.0 171 64 bit

No matter what I do, I can't get the rain to stop here. I've done the totemic drought ceremony, /toggledownfall, /weather clear, nothing I can think of works.

Without building some form of covering, I have no way to fight endermen here.

I've seen it not rain before, but I should be able to make it stop raining with one of the aforementioned methods, hence the issue report.

Seems like this would be an issue related to this mod specifically, if I'm mistaken I'll gladly move this report to the SevTech issue tracker.

**Comment by Fosnez** [comment]
I'm also getting this on Sevtech 3.0.8.

Could it be because in here:

https://github.com/Darkhax-Minecraft/Hunting-Dimension/blob/master/src/main/java/net/darkhax/huntingdim/dimension/WorldProviderHunting.java

The time is always being overwritten / set as midnight, so the rain can't naturally stop after a day or so?

**Comment by monodemono** [comment]
I suspected that was the case, but I wasn't sure that that would effect the totemic ceremony, /toggledownfall, or /weather clear.

Though I suppose it could be that the function where rain stops requires a certain amount of time to pass to complete.

**Comment by Darkhax** [comment]
I am still digging into it, and it is a bit weird. Removing the code that enforces world time does not fix this issue. Only way to disable rain from what I can tell is to run the command and then reload the world. May be a vanilla bug, or I may be an idiot.
