### ISSUE TITLE
Villages spawning even with config set to false.

### ISSUE THREAD

**Issue by KelleyEngineering** [Darkhax-Minecraft/Hunting-Dimension#18]
Minecraft: 1.12.2
Pack: user made
Mod version: 1.0.24
Singleplayer
Java: 1.8.0 171 64 bit

As stated in the title, villages will continue to spawn in the Hunting Dimension despite having set the associated config to "false"

Having a look at it closer, the villages that spawn in the HD seem to be random however if a village exists in the Overworld, it will be copied block for block in the HD. Even the blacksmith loot and villager trades are the same.

I'm more than likely doing something wrong, request if a workaround is possible?

![hunting dim](https://user-images.githubusercontent.com/27598014/40941116-e39e4664-6817-11e8-961e-c6ac7c6c59dc.png)

**Comment by Darkhax** [comment]
Hello, could you give me a world seed to test this?

**Comment by KelleyEngineering** [comment]
-3902778773898349583
  This seed has no village in the overworld but does have a village in it's HD equivalent. Just make a portal when you spawn in

7264166762966979679
  This seed has a village close to Overworld spawn ( x: -176, z: -8) with an identical village in the HD, complete with the same blacksmith loot.

The only mods I put in for this test are Bookshelf 2.3.544 and Hunting Dimension 1.0.24. world_generator_settings.json is identical to what is posted above and I've added the what I had for huntingdim.cfg to this post. Minecraft version 1.12.2, and Forge version 14.23.4.2705

Thank you for looking into this. 

![hunting dim2](https://user-images.githubusercontent.com/27598014/40959760-ace9cd10-686b-11e8-9fb3-795a99cf73fa.png)

**Comment by KelleyEngineering** [comment]
I deleted the world_generator_config.json and allowed the pack to recreate it. The problem did not recreate itself so I'll close this issue.
