### ISSUE TITLE
Bookshelf dependency won't auto-download alpha on Twitch

### ISSUE THREAD

**Issue by kythorn** [Darkhax-Minecraft/Hunting-Dimension#2]
Hi Darkhax,

This isn't really an issue with the mod per se, but...

As of this writing, Twitch won't automatically download the right version of Bookshelf (for most people) at the time of this writing because it's flagged as alpha. This is easy enough to deal with for me, but may confuse many people who are interested in the mod.

Since Hunting Dimension is flagged as a "release build" (1.0.6) and depends on Bookshelf, would it be possible to get a version of bookshelf (2.3.510 or higher) flagged as at least beta?

**Comment by Darkhax** [comment]
Thanks for the report. I've marked a valid release.
