### ISSUE TITLE
Players sometimes have their shift key stuck active after exiting the portal

### ISSUE THREAD

**Issue by mezz** [Darkhax-Minecraft/Hunting-Dimension#20]
Seen here, I figured it should be reported even though I haven't reproduced the issue myself: https://www.reddit.com/r/feedthebeast/comments/8q2rt5/sevtech_ages_why_does_my_character_sometimes_pick/e0g11q0/?context=10000

**Comment by mezz** [comment]
This may be a vanilla issue: https://bugs.mojang.com/browse/MC-10657
There is a fix submitted to Forge: https://github.com/MinecraftForge/MinecraftForge/pull/4974

**Comment by Darkhax** [comment]
Nice, thanks for the link to the PR.

**Comment by Darkhax** [comment]
That PR has been merged, so this should hopefully be closable now.
