### ISSUE TITLE
[Savtech] Changing to Darklands type biome

### ISSUE THREAD

**Issue by Mapharazzo** [Darkhax-Minecraft/Hunting-Dimension#22]
I tried to change the chunk to any darklands specific biome and the biome changed to ocean _**when holding only one creeping moss**_. This seems to be fine when holding 2 or more creeping moss - it changed ok.

**Comment by Darkhax** [comment]
Thanks for the report, I will look into it.

**Comment by Darkhax** [comment]
It looks like this issue was simply a description error, where the item was destroyed before the usage message was sent, thus the default biome of ocean being displayed. The biome itself would be updated correctly however.
