### ISSUE TITLE
Non-stop raining in the hunting dimension

### ISSUE THREAD

**Issue by DrSpghetto** [Darkhax-Minecraft/Hunting-Dimension#27]
Its been over 2 hours now and its yet to stop raining, this is not only annoying as its causing lag to some degree it also prevents me from finding any enderman. Any clue how i can change/fix it?

**Comment by Darkhax** [comment]
Which version of the mod are you using?

**Comment by DrSpghetto** [comment]
It stopped raining- after around 4-5 (real life) hours. 
1.0.24 (mc 1.12.2 - sevtech ages)

**Comment by Darkhax** [comment]
Weather update issues were fixed in 1.0.25.
