### ISSUE TITLE
Status messages on Creeping Moss displays twice

### ISSUE THREAD

**Issue by Lykrast** [Darkhax-Minecraft/Hunting-Dimension#28]
Using the Creeping Moss in the Overworld or changing its biome displays the chat message twice per use at a very short interval.

It would also be nice to have them printed in the action bar rather than your chat.

**Comment by Darkhax** [comment]
This should be fixed in the next update. The reason they are in the chat and not the status bar is because many of the messages are very long, and I don't think they look very nice in the status bar.
