### ISSUE TITLE
Portal spawning in walls

### ISSUE THREAD

**Issue by kythorn** [Darkhax-Minecraft/Hunting-Dimension#3]
Hello,

I'm using version 1.0.6 of the mod. My base is underground, and the portal I put in my base seemed to consistently spawn me solid blocks on the other side. I'm not sure what logic it uses for portal spawns, but would it be possible to make it check the surroundings and keep going "up" until there was sufficient room to let the player out without suffocating?

For now I simply moved the portal outside and all is well, but it would be nice if this could be altered. I've never looked into how that works, but an Aroma Mining Dimensionl in the same spot does work (if that helps).

**Comment by Darkhax** [comment]
Improving the portal logic is definitely something I plan to do. Currently it just mimics the vanilla portal behavior.

**Comment by tofof** [comment]
I have a similar problem but reversed; my portal is at y=79 in the overworld. I come out into the hunting dimension at y=64. When I portal back to the overworld, I frequently come out at y=64 beneath my portal, which caused me several suffocation deaths.

**Comment by Darkhax** [comment]
@tofof Your issue should be fixed in [1.0.20](https://minecraft.curseforge.com/projects/hunting-dimension/files/2548007).
