### ISSUE TITLE
Hunting Dimension Does Not Create Void World When Used With Topography

### ISSUE THREAD

**Issue by Darkosto** [Darkhax-Minecraft/Hunting-Dimension#30]
Hello!

When using the topography mod, the HD does not create a void world. Can you please add a Void option?

Thanks!
DarkRoasto

**Comment by Darkhax** [comment]
New config option to allow a void world. I am doing it in a similar way to yunomakegoodmap so if there are lag/lighting issues please let me know and I will talk with Blargerist and/or mezz about fixing them.
