### ISSUE TITLE
[Suggestion] Specific Mob spawn?

### ISSUE THREAD

**Issue by ReiDaTecnologia** [Darkhax-Minecraft/Hunting-Dimension#37]
Will be really cool if we could change a chunk (like biome change does) to spawn only one specific mob for a certain time or not (configurable)
to make the item that does it, could be like Woot:
Hit the desired mob with the item and it will be configured for that mob
Kill X times that mob to it become configured

maybe an option that to be able to configure the item you need to kill the desired mob only in the hunting dimension?

**Comment by Darkhax** [comment]
Thanks for the feature request. I like the idea, but I feel like it may be kind of out of scope for this mod. Sounds like it would be better as something in another mod. This idea could also be solved by using things like mob spawners?

**Comment by ReiDaTecnologia** [comment]
Yup, mob spawner always can fix it even without using energy (like this idea would do) but if you think it's out of scope for the mod it's fine. It was just a random idea that come in my mind and thought in suggest it.
Nice mod btw!
