### ISSUE TITLE
Crash on World load

### ISSUE THREAD

**Issue by Blatts12** [Darkhax-Minecraft/Hunting-Dimension#38]
I added mod to my modpack and tried to load to my world

https://paste.dimdev.org/suqapanepo.mccrash

**Comment by Darkhax** [comment]
Thanks for the issue report. This should be fixed in newer versions. Did you configure the mod at all before using it? The issue would suggest that something is wrong in your config, or that another mod has created a bugged world type. Should be fixed either way.

**Comment by Blatts12** [comment]
I didn't configure anything but after some research i changed mimicSurfaceWorld to true and everything started working.
