### ISSUE TITLE
Portal is lit. Nothing happens

### ISSUE THREAD

**Issue by Oddwin** [Darkhax-Minecraft/Hunting-Dimension#39]
So, We are playing PO3 and have just built our hunting dimension portal but it wont teleport. 

We have a Nether portal that works fine and I have been through the all of the issues posted here. 

there is NO error message.. you can just stand in the portal forever. No crash, No 'entity error' just nothing.. 

The server and the client are running V 1.0.36 (they came with PO3.)

Just updated to 1.0.38 (latest release) still nothing.. so weird..

**Comment by Darkhax** [comment]
Thanks for the report, you have to press sneak to go through the portal. Same as the older mining dimension mod.

**Comment by Oddwin** [comment]
Thanx it worked.
