### ISSUE TITLE
No world gen?is it supposed to be like this? (I just made a video to explaine)

### ISSUE THREAD

**Issue by Oddwin** [Darkhax-Minecraft/Hunting-Dimension#40]
I promise I'll leave you alone soon. 

Is this working as intended? 

https://www.youtube.com/watch?v=cSgUQx6f6HM&feature=youtu.be

**Comment by Darkhax** [comment]
The video is saying it's unavailable but it's probably working as intended. In your other issue you mentioned that you're playing Project Ozone 3, which IIRC is a skyblock. The hunting dimension can be configured to mirror the world type of the surface world. So if you were playing with just this mod and made a flat world then the hunting dim would also be flat, or if you did amplified the hunting dim would also be amplified. You can also configure it to be a specific world type instead.

**Comment by Oddwin** [comment]
awesome I'll look into this. Thank you for your time.
