### ISSUE TITLE
Biome Changing Issue

### ISSUE THREAD

**Issue by H4PP3N** [Darkhax-Minecraft/Hunting-Dimension#42]
So I'm playin on SevTechAges Modpack and I created the portal and when I'm using a moss to change the biome in the dimension It's not working but the message about changing the biome appears

**Comment by Darkhax** [comment]
Thanks for the issue report. I have been getting this reported a lot in relation to the SevTech ages pack. I believe that one of the mods in the pack is messing with how biomes are being retrieved by the game. I will keep this issue open and use it as a hub for updates on gathering info. If you have any log files related to this issue that would also be very helpful.

**Comment by Darkhax** [comment]
The initial suspicion seems to be correct. SevTech has some mods that completely replace how biomes work unfortunately.
