### ISSUE TITLE
server entering + exiting issue

### ISSUE THREAD

**Issue by MR-Spagetty** [Darkhax-Minecraft/Hunting-Dimension#44]
almost when ever I enter the hunting dimension on a server it gets stuck on loading terrain and I have to quit minecraft to get into and out of the diamension

**Comment by Darkhax** [comment]
This sounds like you have a bad connection to the server or some other form of de-sync has occurred. This mod has been thoroughly tested on servers without encountering this issue.

**Comment by Yourname942** [comment]
I have this issue and I am the server owner.
