### ISSUE TITLE
Crash on World load

### ISSUE THREAD

**Issue by Cazadorsniper** [Darkhax-Minecraft/Hunting-Dimension#5]
https://pastebin.com/fBy84Anu

Not entirely sure its Hunting Dimension because the crash doesn't mention it.

**Comment by Darkhax** [comment]
I don't *think* this is an issue with the hunting dim. Looking at this specific crash, it has something to do with the game trying to get a mob spawn list for a biome. This is natural behavior and not something this mod accesses. Looking at the vanilla code, I don't even see how this crash would be possible, so I suspect a core mod may be changing this vanilla behavior. 

Does removing the hunting dimension fix this issue? If so, does making a new non-void flat world cause the issue to happen again?

**Comment by Cazadorsniper** [comment]
Removing the mod doesn't fix it, I found the culprit: Increased Mobs. Can close this issue, sorry.

**Comment by Darkhax** [comment]
Glad you could solve it :)
