### ISSUE TITLE
Crash while changing biome of the hunting dimension

### ISSUE THREAD

**Issue by G2159687** [Darkhax-Minecraft/Hunting-Dimension#6]
The game crashes whenever I try to change the biome of the hunting dimension with creeping moss. 

Crash report: https://pastebin.com/qW5vz0er

Maybe there's something wrong with my scala library, but I have difficulty fixing that :(  Please tell me the way of fixing that. Thanks!

**Comment by Darkhax** [comment]
Thanks for the report. This is an issue on my end, I should have a fix out shortly for it.
