### ISSUE TITLE
Hunting Dimension Client Crash

### ISSUE THREAD

**Issue by jusjudge** [Darkhax-Minecraft/Hunting-Dimension#7]
When I updated the mod to 1.0.9, it made my client crash. The report is below.

https://hastebin.com/zubavenupu.sql

**Comment by kythorn** [comment]
Issue with the xmas event code. Doesn't look disable-able via config. Advise rolling back until after the 26th unless Darkhax releases a new build before then.

**Comment by brisingraerowing** [comment]
I believe @thraaawn had a similar issue when working on Compact Machines 2. He ended up hard coding the file paths.

**Comment by davenonymous** [comment]
I'm using [this class](https://github.com/thraaawn/CompactMachines/blob/1.12.1/src/main/java/org/dave/compactmachines3/utility/ResourceLoader.java) to load files from the asset path. It supports development environments as well as adding/overwriting of files via a config folder.

**Comment by Darkhax** [comment]
Yes, this is correct. The code seems to work in a dev environment but not on a normal player setup. It's similar to other code which is why I never tested it. The event code should be disabled now. I am hoping to fix this for future events still though.
