### ISSUE TITLE
NoSuchMethodError 

### ISSUE THREAD

**Issue by Mohron** [Darkhax-Minecraft/Hunting-Dimension#9]
- forge-1.12.2-14.23.2.2624-universal
- HuntingDimension-1.12.2-1.0.13
- Bookshelf-1.12.2-2.3.528

Entered the dim, fell from sky, was murdered by a mob gg... When I tried to go back, this happens. I have to force myself out of the dim with a console command then I'm able to go back in without issue.

https://gist.github.com/Mohron/8f89e5df03badb82bfba13514e863c36

**Comment by Darkhax** [comment]
Thanks for the crash report. I have a fix for it that will be on curse in a few minutes.

**Comment by Darkhax** [comment]
This issue is fixed in the 429ef09 and is available in 1.0.17 on Curse. There is a newer version (1.0.18) wither other fixes that is currently being processed by Curse.
